import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

src = Glob('*.c') + Glob('*.cpp')

CPPPATH = []
CPPPATH += [cwd + '/../..']

# Add SDK
Import('SIFLI_SDK')

objs = DefineGroup('res', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')