from building import *
import os

src = Glob('*.c') + Glob('*.cpp')
cwd = GetCurrentDir()

CPPPATH = [cwd]
CPPPATH += [cwd + '/../..']
CPPPATH += [cwd + '/../../output/res/strings/']

group = DefineGroup('', src, depend = [''], CPPPATH=CPPPATH)

Return('group')